name: Validate Push On Main

on:
  push:
    branches:
      - main
    paths:
      - 'sf/**'

jobs:
  run-test-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Change to SF Directory
        run: |
          cd sf
      - name: Install SFDX
        run: |
          npm i -g @salesforce/cli
          sf --version
      - name: Install sfdxGit delta
        run: |
          echo y | sf plugins install sfdx-git-delta
      - name: Generate Manifest
        run: |
          sf sgd:source:delta --to "HEAD" --from "HEAD~1" --output "."
      - name: Login to Org
        run: |
          echo "${{ secrets.SERVER_KEY }}" > server.key
          sf org login jwt --client-id=${{ secrets.CLIENT_ID }} --username=${{ secrets.SF_USERNAME }} --jwt-key-file=server.key --set-default-dev-hub --alias=DevHub
      - name: Run Tests
        run: |
          sf project deploy validate --manifest=package/package.xml -o DevHub -w 10