name: Validate Push On Main

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sf/**'

jobs:
  run-test-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk
          java -version
      - name: Install SFDX
        run: |
          npm i -g @salesforce/cli
          sf --version
      - name: Install Code Scanner
        run: |
          sf plugins install @salesforce/sfdx-scanner
      - name: Install sfdx-git-delta
        run: |
          echo y | sf plugins install sfdx-git-delta
      - name: Generate Manifest
        run: |
          sf sgd:source:delta --to "HEAD" --from "HEAD~1" --output ".\sf"
      - name: Log In To Org
        run: |
          cd sf
          echo "${{ secrets.SERVER_KEY }}" > server.key
          sf org login jwt --client-id=${{ secrets.CLIENT_ID }} --username=${{ secrets.SF_USERNAME }} --jwt-key-file=server.key --set-default-dev-hub --alias=DevHub
      - name: Run Tests
        run: |
          cd sf
          sf project deploy validate --manifest=package/package.xml -o DevHub -w 120
      - name: Run Code Scanner
        run: |
          cd sf
          sf scanner run --target . -f csv -o codescan.csv
          skip_headers = 1
          cat codescan.csv | while IFS=, read -r problem severity file line column rule description url category engine
          do
            if((skip_headers-- > 0))
            then
              continue
            fi
            echo "::warning file=${file},line=${line},col=${column}::${description}"
          done 