name: Validate Push On Main

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sf/force-app/main/default/**'
      - 'sf/scripts/js/**'

jobs:
  run-test-classes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk
          java -version
      - name: Install SFDX
        run: |
          npm i -g @salesforce/cli
          sf --version
      - name: Install Code Scanner
        run: |
          sf plugins install @salesforce/sfdx-scanner
      - name: Run Code Scanner
        run: |
          cd sf
          sf scanner run --target . -f json -o codescan.json
      - name: Raise Warnings
        run: |
          cd sf
          node scripts/js/raise-warnings.js
      - name: Install sfdx-git-delta
        run: |
          echo y | sf plugins install sfdx-git-delta
      - name: Generate Manifest
        run: |
          sf sgd:source:delta --to "HEAD" --from "HEAD~1" --output ".\sf"
      - name: Log In To Org
        run: |
          cd sf
          echo "${{ secrets.SERVER_KEY }}" > server.key
          sf org login jwt --client-id=${{ secrets.CLIENT_ID }} --username=${{ secrets.SF_USERNAME }} --jwt-key-file=server.key --set-default-dev-hub --alias=DevHub
      - name: Validate Against Org
        run: |
          cd sf
          sf project deploy validate --manifest=package/package.xml -o DevHub -w 120